# python/m4/m4_2_newsletter_agent.py
"""Module 4 · Lesson 2 — Building a subagent team.

An "editor" main agent delegates each of the distributor's top music genres to
a single `genre-researcher` subagent type, run in parallel. Each researcher
web-searches its genre, keeps the raw results in an assigned /research/<genre>/
scratch folder, and returns one short article segment. The editor assembles the
segments and writes a styled HTML newsletter to /output/newsletter.html.

The agent runs on the default (ephemeral) StateBackend — it never touches the
real local filesystem. The companion m4.2_run_newsletter.py extracts the finished HTML from agent state
and writes it to disk.
"""

import os

import markdown as md
import nh3
from deepagents import FilesystemPermission, create_deep_agent
from langchain_core.tools import tool
from tavily import TavilyClient

from models import model, strong_model

# The distributor's top genres — known up front, no database needed.
TOP_GENRES = ["Rock", "Latin", "Metal", "Alternative & Punk"]


# --- Tools -----------------------------------------------------------------
# internet_search belongs ONLY to the subagent (see `tools=` below).
tavily_api_key = os.environ.get("TAVILY_API_KEY")
if not tavily_api_key:
    raise RuntimeError(
        "TAVILY_API_KEY is required for the Module 4.2 newsletter lab. "
        "Set it in your environment before running m4.2_run_newsletter.py."
    )

_tavily = TavilyClient(api_key=tavily_api_key)


@tool
def internet_search(query: str, max_results: int = 8) -> dict:
    """Search the web for recent news. Use this to research what's new in a
    music genre — new releases, notable artists, trends, and events."""
    return _tavily.search(query, max_results=max_results, topic="news")


# markdown_to_html belongs ONLY to the editor (the main agent).
# The template is a fixed, static string. NOTE: in production you would
# sanitize model/search-derived text before rendering it to HTML.
_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ max-width: 760px; margin: 40px auto; padding: 0 20px;
          font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
          line-height: 1.6; color: #1a1a1a; }}
  h1 {{ font-size: 2rem; border-bottom: 3px solid #006DDD; padding-bottom: .3em; }}
  h2 {{ color: #006DDD; margin-top: 1.6em; }}
  footer {{ margin-top: 3em; color: #777; font-size: .85rem;
            border-top: 1px solid #ddd; padding-top: 1em; }}
</style>
</head>
<body>
{body}
<footer>Generated by a Deep Agents subagent team.</footer>
</body>
</html>"""


@tool
def markdown_to_html(markdown_text: str, title: str = "This Week in Music") -> str:
    """Convert a Markdown newsletter into a complete, styled HTML page.
    Returns the full HTML document as a string."""
    body = md.markdown(markdown_text, extensions=["tables", "fenced_code"])
    # Good practice: the newsletter text is derived from untrusted web search,
    # so allowlist-sanitize it (strips <script>, onerror=, etc.) before it goes
    # into the page. We clean only the body; the template itself is trusted.
    body = nh3.clean(body)
    return _HTML_TEMPLATE.format(title=title, body=body)


# --- The research subagent -------------------------------------------------
GENRE_PROMPT = """You are a music journalist researching one genre for an
online music distributor's weekly newsletter.

You will be given a single genre and an assigned research folder to work in.

How to work:
1. Use internet_search to find recent, noteworthy developments in that genre
   — new releases, notable artists, trends, or events. Run a few searches.
2. Save the COMPLETE, verbatim output of ALL your searches to a single file:
   write_file("/research/<genre>/sources.md", ...). Paste the results exactly
   as the tool returned them — every result's title, URL, and full content
   snippet. Do NOT summarize, trim, or reformat. This one file is your raw
   archive: all the bulky material stays here so it never clutters the
   editor's context.
3. Only then, from what you found, write one tight newsletter segment.

Return ONLY the finished segment as your reply:
- A markdown section: a "## <Genre>" heading followed by ~120-180 words.
- Lively but factual newsletter tone; name specific artists and releases.
- Do NOT paste raw search results or link dumps into your reply — those live
  in your research files. Return just the polished segment."""

# Researchers may write under /research/** and are denied writes elsewhere.
research_permissions = [
    FilesystemPermission(operations=["read", "write"], paths=["/research/**"], mode="allow"),
    FilesystemPermission(operations=["write"], paths=["/**"], mode="deny"),
]

genre_researcher = {
    "name": "genre-researcher",
    "description": (
        "Research one music genre and write a short newsletter segment about "
        "what's new in it. Delegate one genre per call."
    ),
    "system_prompt": GENRE_PROMPT,         # its own brain — never inherited
    "tools": [internet_search],            # override — replaces the inherited set
    "model": model,                        # override — the cheaper Haiku 4.5
    "permissions": research_permissions,   # override — scoped write access
}


# --- The editor (main agent) -----------------------------------------------
EDITOR_PROMPT = f"""You are the editor of an online music distributor's weekly
newsletter. This week you are featuring the distributor's top genres:
{", ".join(TOP_GENRES)}.

Your job:
1. For EACH genre, delegate to the genre-researcher subagent using the task
   tool — fire them off in parallel. Tell each one which genre to cover and
   which assigned folder to use (/research/<genre>/), and ask for one segment.
2. Collect the four returned segments. Do NOT research genres yourself.
3. Assemble them into one Markdown newsletter: a top-level "# This Week in
   Music" title, a one-sentence intro, then the four "## <Genre>" sections.
4. Call markdown_to_html on the assembled Markdown, then write_file the
   returned HTML to /output/newsletter.html.

Keep your own context focused on coordination and assembly."""

# The editor uses the stronger shared model; the researcher overrides to the
# cheaper `model` (Haiku 4.5) above. Both come from models.py.

# The editor may read the research area but must not write into it.
editor_permissions = [
    FilesystemPermission(operations=["write"], paths=["/research/**"], mode="deny"),
]

agent = create_deep_agent(
    model=strong_model,
    tools=[markdown_to_html],
    system_prompt=EDITOR_PROMPT,
    subagents=[genre_researcher],
    permissions=editor_permissions,
)
